### PR TITLE
refactor(app_theme): move theme to app_ui folder

### PR DESCRIPTION
**Pull request by kamilgadek**

### CODE REVIEW

**Review by mszakacz — CHANGES_REQUESTED** [review]
@kamilgadek do one step at the time,
first take https://github.com/kamilgadek/to_do_list_kamilg/issues/25 and CREATE the new package only.
Then, as separate PR, move the files to the specific location: refer to the good example I gave you in https://github.com/kamilgadek/to_do_list_kamilg/issues/26

**Comment by mszakacz** [comment]
@kamilgadek  please rename a PR name. As you want to create a new package only, name it: `feat(app_ui): create package`

**Comment by kamilgadek** [comment]
ok i make new brunch please delete this one

**Comment by mszakacz** [comment]
> ok i made new brunch , can i close and delete that one?

@kamilgadek sure, let's delete it as you have already created new PR

**Pull request closed without merging**
